apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.gitservice.devopsconsole.openshift.io
spec:
  insecureSkipTLSVerify: true
  group: gitservice.devopsconsole.openshift.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: openshift-devops-console
  version: v1alpha1
