apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitservice-devopsconsole-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: gitapiserver
  namespace: openshift-devops-console
