apiVersion: v1
kind: ReplicationController
metadata:
  name: gitservice-devopsconsole-apiserver
  namespace: openshift-devops-console
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: gitservice-devopsconsole-apiserver
        # Replace this with the built image name
        image: REPLACE_IMAGE
        imagePullPolicy: Always
        command: [ "/git-service", "--etcd-servers=http://localhost:2379" ]
        volumeMounts:
        - mountPath: /tmp/kube-apiserver-audit.log
          name: audit-log
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.18
      volumes:
        - name: audit-log
          hostPath:
            path: /tmp/kube-apiserver-audit.log
            type: FileOrCreate
