DOCKER_REPO?=quay.io/openshiftio
IMAGE_NAME?=git-service
SHORT_COMMIT=$(shell git rev-parse --short HEAD)
ifneq ($(GITUNTRACKEDCHANGES),)
SHORT_COMMIT := $(SHORT_COMMIT)-dirty
endif

TIMESTAMP:=$(shell date +%s)
TAG?=$(SHORT_COMMIT)-$(TIMESTAMP)

DEPLOY_DIR:=deploy

.PHONY: create-resources
create-resources:
	@echo "Logging using system:admin..."
	@oc login -u system:admin
	@echo "Creating sub resources..."
	@echo "Creating CRDs..."
	@oc create -f https://raw.githubusercontent.com/redhat-developer/devconsole-operator/master/deploy/crds/devopsconsole_v1alpha1_gitsource_crd.yaml
	@echo "Creating Namespace"
	@oc create -f $(DEPLOY_DIR)/namespace.yaml

.PHONY: build-image
build-image:
	docker build -t $(DOCKER_REPO)/$(IMAGE_NAME):$(TAG) -f Dockerfile.dev .
	docker tag $(DOCKER_REPO)/$(IMAGE_NAME):$(TAG) $(DOCKER_REPO)/$(IMAGE_NAME):test

.PHONY: deploy-gitserver-only
deploy-gitserver-only:
	@echo "Creating Git Server..."

.PHONY: clean-all
clean-all:  clean-gitserver clean-resources

.PHONY: clean-gitserver
clean-gitserver:
	@echo "Deleting API Server..."

.PHONY: clean-resources
clean-resources:
	@echo "Deleting sub resources..."
	@echo "Deleting Namespace"
	@oc delete -f $(DEPLOY_DIR)/namespace.yaml || true
	@echo "Deleting CRDs..."
	@oc delete -f https://raw.githubusercontent.com/redhat-developer/devconsole-operator/master/deploy/crds/devopsconsole_v1alpha1_gitsource_crd.yaml || true

.PHONY: deploy-gitserver
deploy-gitserver: build build-image deploy-gitserver-only

.PHONY: minishift-start
minishift-start:
	minishift start --cpus 4 --memory 8GB
	-eval `minishift docker-env` && oc login -u system:admin

.PHONY: deploy-all
deploy-all: clean-resources create-resources deps prebuild-check deploy-gitserver
